version: "3"
services:
  namenode:
    image: leesper/hadoop-namenode:3.0.3
    hostname: hadoop.name
    volumes:
      - namenode-vol:/data/hadoop/name
    env_file:
      - ./hadoop.env
  historyserver:
    image: leesper/hadoop-historyserver:3.0.3
    depends_on:
      - namenode
    hostname: hadoop.historyserver
    volumes:
      - historyserver-vol:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
  mrhistoryserver:
    image: leesper/hadoop-mrhistoryserver:3.0.3
    depends_on:
      - namenode
    hostname: hadoop.mrjobhistoryserver
    env_file:
      - ./hadoop.env
  datanode-1:
    image: leesper/hadoop-datanode:3.0.3
    depends_on:
      - namenode
    hostname: hadoop.datanode-1
    volumes:
      - datanode-1-vol:/data/hadoop/data
    env_file:
      - ./hadoop.env
  datanode-2:
    image: leesper/hadoop-datanode:3.0.3
    depends_on:
      - namenode
    hostname: hadoop.datanode-2
    volumes:
      - datanode-2-vol:/data/hadoop/data
    env_file:
      - ./hadoop.env
  resourcemanager:
    image: leesper/hadoop-resourcemanager:3.0.3
    depends_on:
      - namenode
    hostname: hadoop.resourcemanager
    env_file:
      - ./hadoop.env
  nodemanager:
    image: leesper/hadoop-nodemanager:3.0.3
    hostname: hadoop.nodemanager
    depends_on:
      - namenode
      - resourcemanager
    env_file:
      - ./hadoop.env
volumes:
  namenode-vol:
  datanode-1-vol:
  datanode-2-vol:
  historyserver-vol: